In [1]:
import pandas as pd
import holoviews as hv
import panel as pn
from src.data.make_dataset import DATA_PATH

In [2]:
df = pd.read_csv('../data/raw/StockUniteLegale_utf8.csv')

/var/folders/5z/39x2t1v937l2htjdr2vrlnhr0000gn/T/ipykernel_32424/4268918832.py:1: DtypeWarning: Columns (2,4,5,6,7,8,9,10,11,12,13,17,21,22,24,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/raw/StockUniteLegale_utf8.csv')

In [3]:
df.describe()

,siren,anneeEffectifsUniteLegale,nombrePeriodesUniteLegale,anneeCategorieEntreprise,categorieJuridiqueUniteLegale,nicSiegeUniteLegale,societeMissionUniteLegale,caractereEmployeurUniteLegale
count,2.674102e+07,1942330.0,2.674102e+07,9227067.0,2.674102e+07,2.674102e+07,0.0,0.0
mean,6.160810e+08,2021.0,2.393328e+00,2021.0,3.285772e+03,1.917153e+01,NaN,NaN
std,2.330876e+08,0.0,1.696373e+00,0.0,2.747179e+03,4.358566e+01,NaN,NaN
min,3.251750e+05,2021.0,1.000000e+00,2021.0,1.000000e+03,1.000000e+00,NaN,NaN
25%,4.094037e+08,2021.0,1.000000e+00,2021.0,1.000000e+03,1.300000e+01,NaN,NaN
50%,5.239602e+08,2021.0,2.000000e+00,2021.0,1.000000e+03,1.600000e+01,NaN,NaN
75%,8.401071e+08,2021.0,3.000000e+00,2021.0,5.599000e+03,2.100000e+01,NaN,NaN
max,9.999924e+08,2021.0,7.100000e+01,2021.0,9.970000e+03,7.627900e+04,NaN,NaN